# sleep.sub -- simple sleep job
executable              = /afs/cern.ch/user/i/ihaque/scannerS/ScannerS-master/build/sh-bbyy-pheno/testing/SusHi_HiggsCrossSections/SusHiCondor/condorExecutable.sh

getenv                  = True
log                     = condor.log
output                  = condor.out
error                   = condor.err

# longlunch = 2 hrs
+JobFlavour             = "workday"

queue
